#!/bin/sh

scripts/load-build || exit 255 # Abort bisection

echo "Build ready. Go test it!"

# Prompt the user in order to return the correct status code to git-bisect
while true; do
	printf "git bisect [good/bad/old/new]: "
	read -r yn
	case $yn in
		good|old) status=0; break;;
		bad|new) status=1; break;;
	esac
done

git checkout -- gutenberg.php

exit $status
