#!/bin/sh

scripts/load-build || exit 255 # Abort bisection

echo "Build ready. Go test it!"

# Prompt the user in order to return the correct status code to git-bisect
while true; do
	printf "git bisect [good/bad/old/new]: "
	read -r yn
	case $yn in
		good|old) exit 0;;
		bad|new) exit 1;;
	esac
done
